// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/GeorgeS1995/mafia_bot/internal/discord (interfaces: MafiaBotInterfaces)

// Package discord is a generated GoMock package.
package discord

import (
	reflect "reflect"

	discordgo "github.com/bwmarrin/discordgo"
	gomock "github.com/golang/mock/gomock"
)

// MockMafiaBotInterfaces is a mock of MafiaBotInterfaces interface.
type MockMafiaBotInterfaces struct {
	ctrl     *gomock.Controller
	recorder *MockMafiaBotInterfacesMockRecorder
}

// MockMafiaBotInterfacesMockRecorder is the mock recorder for MockMafiaBotInterfaces.
type MockMafiaBotInterfacesMockRecorder struct {
	mock *MockMafiaBotInterfaces
}

// NewMockMafiaBotInterfaces creates a new mock instance.
func NewMockMafiaBotInterfaces(ctrl *gomock.Controller) *MockMafiaBotInterfaces {
	mock := &MockMafiaBotInterfaces{ctrl: ctrl}
	mock.recorder = &MockMafiaBotInterfacesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMafiaBotInterfaces) EXPECT() *MockMafiaBotInterfacesMockRecorder {
	return m.recorder
}

// ChannelMessageSend mocks base method.
func (m *MockMafiaBotInterfaces) ChannelMessageSend(arg0, arg1 string) (*discordgo.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChannelMessageSend", arg0, arg1)
	ret0, _ := ret[0].(*discordgo.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChannelMessageSend indicates an expected call of ChannelMessageSend.
func (mr *MockMafiaBotInterfacesMockRecorder) ChannelMessageSend(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChannelMessageSend", reflect.TypeOf((*MockMafiaBotInterfaces)(nil).ChannelMessageSend), arg0, arg1)
}

// GuildChannels mocks base method.
func (m *MockMafiaBotInterfaces) GuildChannels(arg0 string) ([]*discordgo.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GuildChannels", arg0)
	ret0, _ := ret[0].([]*discordgo.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GuildChannels indicates an expected call of GuildChannels.
func (mr *MockMafiaBotInterfacesMockRecorder) GuildChannels(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GuildChannels", reflect.TypeOf((*MockMafiaBotInterfaces)(nil).GuildChannels), arg0)
}
