#!/bin/bash

touch mafia-bot.env
cat << EOF >> mafia-bot.env
MAFIA_BOT_DB_PASSWORD=$DB_PASSWORD
MAFIA_BOT_DB_USER=$DB_USER
MAFIA_BOT_DB_NAME=$DB_NAME
MAFIA_BOT_DISCORD_TOKEN=$MAFIA_BOT_DISCORD_TOKEN
MAFIA_BOT_STATUS_CHANNELS=$MAFIA_BOT_STATUS_CHANNELS
MAFIA_BOT_STATISTIC_CHANNEL=$MAFIA_BOT_STATISTIC_CHANNEL
MAFIA_BOT_CSRF=$MAFIA_BOT_CSRF
MAFIA_BOT_CSRF_COOKIE=$MAFIA_BOT_CSRF_COOKIE
MAFIA_BOT_POLEMICA_HOST=$MAFIA_BOT_POLEMICA_HOST
MAFIA_BOT_POLEMICA_LOGIN=$MAFIA_BOT_POLEMICA_LOGIN
MAFIA_BOT_POLEMICA_PASSWORD=$MAFIA_BOT_POLEMICA_PASSWORD
EOF
touch mafia-db.env
cat << EOF >> mafia-db.env
POSTGRES_PASSWORD=$DB_PASSWORD
POSTGRES_USER=$DB_USER
POSTGRES_DB=$DB_NAME
EOF